version: "3"
services:
  mongodb:
    image: mongo
   
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    depends_on: 
     - "mongodb"
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
     - ME_CONFIG_MONGODB_SERVER=mongodb
  node:
    image: public.ecr.aws/i8h9e8u6/first-app:1.0
    depends_on:
      - "mongodb"
    ports:
     - 8080:8080


